-- DBOS system database schema fixture.
--
-- Generated by concatenating the Postgres-path migrations from
-- reference/dbos-transact-golang/dbos/internal/sysdb/migrations/, in the
-- exact order and with the exact per-migration variant selection performed
-- by BuildMigrations() in
-- reference/dbos-transact-golang/dbos/internal/sysdb/system_database.go
-- (isCockroach = false). Target schema is hardcoded to "dbos" in place of
-- the %s placeholders the Go code fills via fmt.Sprintf.
--
-- CONCURRENTLY is kept on the index migrations that use it in the real
-- Postgres path; psql applies each statement outside an explicit
-- transaction block by default, so this is safe to run via
-- `psql -f priv/schema/dbos_schema.sql`.

CREATE SCHEMA IF NOT EXISTS "dbos";

CREATE TABLE "dbos".dbos_migrations (version BIGINT NOT NULL PRIMARY KEY);

-- migration 1: 1_initial_dbos_schema.sql

CREATE TABLE "dbos".workflow_status (
    workflow_uuid TEXT PRIMARY KEY,
    status TEXT,
    name TEXT,
    authenticated_user TEXT,
    assumed_role TEXT,
    authenticated_roles TEXT,
    request TEXT,
    output TEXT,
    error TEXT,
    executor_id TEXT,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(epoch FROM now())::numeric * 1000)::bigint,
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(epoch FROM now())::numeric * 1000)::bigint,
    application_version TEXT,
    application_id TEXT,
    class_name VARCHAR(255) DEFAULT NULL,
    config_name VARCHAR(255) DEFAULT NULL,
    recovery_attempts BIGINT DEFAULT 0,
    queue_name TEXT,
    workflow_timeout_ms BIGINT,
    workflow_deadline_epoch_ms BIGINT,
    inputs TEXT,
    started_at_epoch_ms BIGINT,
    deduplication_id TEXT,
    priority INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX workflow_status_created_at_index ON "dbos".workflow_status (created_at);
CREATE INDEX workflow_status_executor_id_index ON "dbos".workflow_status (executor_id);
CREATE INDEX workflow_status_status_index ON "dbos".workflow_status (status);

ALTER TABLE "dbos".workflow_status
ADD CONSTRAINT uq_workflow_status_queue_name_dedup_id
UNIQUE (queue_name, deduplication_id);

CREATE TABLE "dbos".operation_outputs (
    workflow_uuid TEXT NOT NULL,
    function_id INTEGER NOT NULL,
    function_name TEXT NOT NULL DEFAULT '',
    output TEXT,
    error TEXT,
    child_workflow_id TEXT,
    PRIMARY KEY (workflow_uuid, function_id),
    FOREIGN KEY (workflow_uuid) REFERENCES "dbos".workflow_status(workflow_uuid)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "dbos".notifications (
    destination_uuid TEXT NOT NULL,
    topic TEXT,
    message TEXT NOT NULL,
    created_at_epoch_ms BIGINT NOT NULL DEFAULT (EXTRACT(epoch FROM now())::numeric * 1000)::bigint,
    message_uuid TEXT NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY, -- Built-in function
    FOREIGN KEY (destination_uuid) REFERENCES "dbos".workflow_status(workflow_uuid)
        ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE INDEX idx_workflow_topic ON "dbos".notifications (destination_uuid, topic);

CREATE TABLE "dbos".workflow_events (
    workflow_uuid TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (workflow_uuid, key),
    FOREIGN KEY (workflow_uuid) REFERENCES "dbos".workflow_status(workflow_uuid)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "dbos".streams (
    workflow_uuid TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    "offset" INTEGER NOT NULL,
    PRIMARY KEY (workflow_uuid, key, "offset"),
    FOREIGN KEY (workflow_uuid) REFERENCES "dbos".workflow_status(workflow_uuid)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE "dbos".event_dispatch_kv (
    service_name TEXT NOT NULL,
    workflow_fn_name TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT,
    update_seq NUMERIC(38,0),
    update_time NUMERIC(38,15),
    PRIMARY KEY (service_name, workflow_fn_name, key)
);

-- migration 1: 1_initial_dbos_schema_listen_notify.sql (Postgres-only tail, appended to migration 1)

CREATE OR REPLACE FUNCTION "dbos".notifications_function() RETURNS TRIGGER AS $$
DECLARE
    payload text := NEW.destination_uuid || '::' || NEW.topic;
BEGIN
    PERFORM pg_notify('dbos_notifications_channel', payload);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER dbos_notifications_trigger
AFTER INSERT ON "dbos".notifications
FOR EACH ROW EXECUTE FUNCTION "dbos".notifications_function();

CREATE OR REPLACE FUNCTION "dbos".workflow_events_function() RETURNS TRIGGER AS $$
DECLARE
    payload text := NEW.workflow_uuid || '::' || NEW.key;
BEGIN
    PERFORM pg_notify('dbos_workflow_events_channel', payload);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER dbos_workflow_events_trigger
AFTER INSERT ON "dbos".workflow_events
FOR EACH ROW EXECUTE FUNCTION "dbos".workflow_events_function();

INSERT INTO "dbos".dbos_migrations (version) VALUES (1);

-- migration 2: 2_add_queue_partition_key.sql

ALTER TABLE "dbos".workflow_status
ADD COLUMN queue_partition_key TEXT;

UPDATE "dbos".dbos_migrations SET version = 2;

-- migration 3: 3_add_workflow_status_index.sql

CREATE INDEX "idx_workflow_status_queue_status_started" ON "dbos"."workflow_status" ("queue_name", "status", "started_at_epoch_ms");

UPDATE "dbos".dbos_migrations SET version = 3;

-- migration 4: 4_add_forked_from.sql

ALTER TABLE "dbos".workflow_status
ADD COLUMN forked_from TEXT;

CREATE INDEX "idx_workflow_status_forked_from" ON "dbos"."workflow_status" ("forked_from");

UPDATE "dbos".dbos_migrations SET version = 4;

-- migration 5: 5_add_step_timestamps.sql

ALTER TABLE "dbos".operation_outputs
ADD COLUMN started_at_epoch_ms BIGINT, ADD COLUMN completed_at_epoch_ms BIGINT;

UPDATE "dbos".dbos_migrations SET version = 5;

-- migration 6: 6_add_workflow_events_history.sql

CREATE TABLE "dbos".workflow_events_history (
    workflow_uuid TEXT NOT NULL,
    function_id INTEGER NOT NULL,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    PRIMARY KEY (workflow_uuid, function_id, key),
    FOREIGN KEY (workflow_uuid) REFERENCES "dbos".workflow_status(workflow_uuid)
        ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE "dbos".streams ADD COLUMN function_id INTEGER NOT NULL DEFAULT 0;

UPDATE "dbos".dbos_migrations SET version = 6;

-- migration 7: 7_add_owner_xid.sql

ALTER TABLE "dbos".workflow_status ADD COLUMN owner_xid TEXT DEFAULT NULL;

UPDATE "dbos".dbos_migrations SET version = 7;

-- migration 8: 8_add_parent_workflow_id.sql

ALTER TABLE "dbos".workflow_status
ADD COLUMN parent_workflow_id TEXT DEFAULT NULL;

CREATE INDEX "idx_workflow_status_parent_workflow_id" ON "dbos"."workflow_status" ("parent_workflow_id");

UPDATE "dbos".dbos_migrations SET version = 8;

-- migration 9: 9_add_workflow_schedules.sql

CREATE TABLE "dbos".workflow_schedules (
    schedule_id TEXT PRIMARY KEY,
    schedule_name TEXT NOT NULL UNIQUE,
    workflow_name TEXT NOT NULL,
    workflow_class_name TEXT,
    schedule TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    context TEXT NOT NULL
);

UPDATE "dbos".dbos_migrations SET version = 9;

-- migration 10: 10_add_notifications_pkey.sql (Postgres variant; CockroachDB uses the
-- 10_check_notifications_pkey_cockroach.sql / 10_add_notifications_pkey_cockroach.sql
-- pair driven from Go via applyCockroachMigration10, not a raw SQL file)

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint c
        JOIN pg_class cl ON c.conrelid = cl.oid
        JOIN pg_namespace n ON cl.relnamespace = n.oid
        WHERE n.nspname = 'dbos'
          AND cl.relname = 'notifications'
          AND c.contype = 'p'
    ) THEN
        ALTER TABLE "dbos".notifications ADD PRIMARY KEY (message_uuid);
    END IF;
END $$;

UPDATE "dbos".dbos_migrations SET version = 10;

-- migration 11: 11_add_serialization_columns.sql

ALTER TABLE "dbos".workflow_status ADD COLUMN serialization TEXT DEFAULT NULL;
ALTER TABLE "dbos".notifications ADD COLUMN serialization TEXT DEFAULT NULL;
ALTER TABLE "dbos".workflow_events ADD COLUMN serialization TEXT DEFAULT NULL;
ALTER TABLE "dbos".workflow_events_history ADD COLUMN serialization TEXT DEFAULT NULL;
ALTER TABLE "dbos".operation_outputs ADD COLUMN serialization TEXT DEFAULT NULL;
ALTER TABLE "dbos".streams ADD COLUMN serialization TEXT DEFAULT NULL;

UPDATE "dbos".dbos_migrations SET version = 11;

-- migration 12: 12_add_notifications_consumed.sql

ALTER TABLE "dbos".notifications ADD COLUMN consumed BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX "idx_notifications" ON "dbos".notifications (destination_uuid, topic);

UPDATE "dbos".dbos_migrations SET version = 12;

-- migration 13: 13_add_application_versions.sql

CREATE TABLE "dbos".application_versions (
    version_id TEXT NOT NULL PRIMARY KEY,
    version_name TEXT NOT NULL UNIQUE,
    version_timestamp BIGINT NOT NULL DEFAULT (EXTRACT(epoch FROM now())::numeric * 1000)::bigint,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(epoch FROM now())::numeric * 1000)::bigint
);

UPDATE "dbos".dbos_migrations SET version = 13;

-- migration 14: 14_add_pgsql_client_functions.sql

CREATE FUNCTION "dbos".enqueue_workflow(
    workflow_name TEXT,
    queue_name TEXT,
    positional_args JSON[] DEFAULT ARRAY[]::JSON[],
    named_args JSON DEFAULT '{}'::JSON,
    class_name TEXT DEFAULT NULL,
    config_name TEXT DEFAULT NULL,
    workflow_id TEXT DEFAULT NULL,
    app_version TEXT DEFAULT NULL,
    timeout_ms BIGINT DEFAULT NULL,
    deadline_epoch_ms BIGINT DEFAULT NULL,
    deduplication_id TEXT DEFAULT NULL,
    priority INTEGER DEFAULT NULL,
    queue_partition_key TEXT DEFAULT NULL
) RETURNS TEXT AS $$
DECLARE
    v_workflow_id TEXT;
    v_serialized_inputs TEXT;
    v_owner_xid TEXT;
    v_now BIGINT;
    v_recovery_attempts INTEGER := 0;
    v_priority INTEGER;
BEGIN

    IF workflow_name IS NULL OR workflow_name = '' THEN
        RAISE EXCEPTION 'Workflow name cannot be null or empty';
    END IF;
    IF queue_name IS NULL OR queue_name = '' THEN
        RAISE EXCEPTION 'Queue name cannot be null or empty';
    END IF;
    IF named_args IS NOT NULL AND jsonb_typeof(named_args::jsonb) != 'object' THEN
        RAISE EXCEPTION 'Named args must be a JSON object';
    END IF;
    IF workflow_id IS NOT NULL AND workflow_id = '' THEN
        RAISE EXCEPTION 'Workflow ID cannot be an empty string if provided.';
    END IF;

    v_workflow_id := COALESCE(workflow_id, gen_random_uuid()::TEXT);
    v_owner_xid := gen_random_uuid()::TEXT;
    v_priority := COALESCE(priority, 0);
    v_serialized_inputs := json_build_object(
        'positionalArgs', positional_args,
        'namedArgs', named_args
    )::TEXT;
    v_now := EXTRACT(epoch FROM now()) * 1000;

    INSERT INTO "dbos".workflow_status (
        workflow_uuid, status, inputs,
        name, class_name, config_name,
        authenticated_user, assumed_role,
        queue_name, deduplication_id, priority, queue_partition_key,
        application_version,
        created_at, updated_at, recovery_attempts,
        workflow_timeout_ms, workflow_deadline_epoch_ms,
        parent_workflow_id, owner_xid, serialization
    ) VALUES (
        v_workflow_id, 'ENQUEUED', v_serialized_inputs,
        workflow_name, class_name, config_name,
        '', '',
        queue_name, deduplication_id, v_priority, queue_partition_key,
        app_version,
        v_now, v_now, v_recovery_attempts,
        timeout_ms, deadline_epoch_ms,
        NULL, v_owner_xid, 'portable_json'
    )
    ON CONFLICT (workflow_uuid)
    DO UPDATE SET
        updated_at = EXCLUDED.updated_at;

    RETURN v_workflow_id;

EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION 'DBOS queue duplicated'
            USING DETAIL = format('Workflow %s with queue %s and deduplication ID %s already exists', v_workflow_id, queue_name, deduplication_id),
                ERRCODE = 'unique_violation';
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION "dbos".send_message(
    destination_id TEXT,
    message JSON,
    topic TEXT DEFAULT NULL,
    message_id TEXT DEFAULT NULL
) RETURNS VOID AS $$
DECLARE
    v_topic TEXT := COALESCE(topic, '__null__topic__');
    v_message_id TEXT := COALESCE(message_id, gen_random_uuid()::TEXT);
BEGIN
    INSERT INTO "dbos".notifications (
        destination_uuid, topic, message, message_uuid, serialization
    ) VALUES (
        destination_id, v_topic, message, v_message_id, 'portable_json'
    )
    ON CONFLICT (message_uuid) DO NOTHING;
EXCEPTION
    WHEN foreign_key_violation THEN
        RAISE EXCEPTION 'DBOS non-existent workflow'
            USING DETAIL = format('Destination workflow %s does not exist', destination_id),
                ERRCODE = 'foreign_key_violation';
END;
$$ LANGUAGE plpgsql;

UPDATE "dbos".dbos_migrations SET version = 14;

-- migration 15: 15_add_workflow_schedule_columns.sql

ALTER TABLE "dbos".workflow_schedules ADD COLUMN "last_fired_at" TEXT DEFAULT NULL;
ALTER TABLE "dbos".workflow_schedules ADD COLUMN "automatic_backfill" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "dbos".workflow_schedules ADD COLUMN "cron_timezone" TEXT DEFAULT NULL;

UPDATE "dbos".dbos_migrations SET version = 15;

-- migration 16: 16_add_delay_until.sql

ALTER TABLE "dbos".workflow_status ADD COLUMN "delay_until_epoch_ms" BIGINT DEFAULT NULL;
CREATE INDEX "idx_workflow_status_delayed" ON "dbos".workflow_status ("delay_until_epoch_ms") WHERE status = 'DELAYED';

UPDATE "dbos".dbos_migrations SET version = 16;

-- migration 17: 17_add_workflow_schedule_queue_name.sql

ALTER TABLE "dbos".workflow_schedules ADD COLUMN "queue_name" TEXT DEFAULT NULL;

UPDATE "dbos".dbos_migrations SET version = 17;

-- migration 18: 18_add_was_forked_from.sql

ALTER TABLE "dbos"."workflow_status" ADD COLUMN "was_forked_from" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE "dbos".dbos_migrations SET version = 18;

-- migration 19: 19_add_operation_outputs_completed_at_index.sql

CREATE INDEX "idx_operation_outputs_completed_at_function_name" ON "dbos"."operation_outputs" ("completed_at_epoch_ms", "function_name");

UPDATE "dbos".dbos_migrations SET version = 19;

-- migration 20: 20_set_function_search_path.sql (Postgres-only; no-op on CockroachDB)

ALTER FUNCTION "dbos".enqueue_workflow(
    TEXT, TEXT, JSON[], JSON, TEXT, TEXT, TEXT, TEXT, BIGINT, BIGINT, TEXT, INTEGER, TEXT
) SET search_path = pg_catalog, pg_temp;

ALTER FUNCTION "dbos".send_message(
    TEXT, JSON, TEXT, TEXT
) SET search_path = pg_catalog, pg_temp;

ALTER FUNCTION "dbos".notifications_function() SET search_path = pg_catalog, pg_temp;
ALTER FUNCTION "dbos".workflow_events_function() SET search_path = pg_catalog, pg_temp;

UPDATE "dbos".dbos_migrations SET version = 20;

-- migration 21: 21_create_queues_table.sql

CREATE TABLE "dbos".queues (
    queue_id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    name TEXT NOT NULL UNIQUE,
    concurrency INTEGER,
    worker_concurrency INTEGER,
    rate_limit_max INTEGER,
    rate_limit_period_sec DOUBLE PRECISION,
    priority_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    partition_queue BOOLEAN NOT NULL DEFAULT FALSE,
    polling_interval_sec DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    created_at BIGINT NOT NULL DEFAULT (EXTRACT(epoch FROM now()) * 1000.0)::bigint,
    updated_at BIGINT NOT NULL DEFAULT (EXTRACT(epoch FROM now()) * 1000.0)::bigint
);

UPDATE "dbos".dbos_migrations SET version = 21;

-- migration 22: 22_drop_forked_from_index.sql (Online: true, CONCURRENTLY)

DROP INDEX CONCURRENTLY IF EXISTS "dbos"."idx_workflow_status_forked_from";

UPDATE "dbos".dbos_migrations SET version = 22;

-- migration 23: 23_create_partial_forked_from_index.sql (Online: true, CONCURRENTLY)

CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_workflow_status_forked_from" ON "dbos"."workflow_status" ("forked_from") WHERE "forked_from" IS NOT NULL;

UPDATE "dbos".dbos_migrations SET version = 23;

-- migration 24: 24_drop_parent_workflow_id_index.sql (Online: true, CONCURRENTLY)

DROP INDEX CONCURRENTLY IF EXISTS "dbos"."idx_workflow_status_parent_workflow_id";

UPDATE "dbos".dbos_migrations SET version = 24;

-- migration 25: 25_create_partial_parent_workflow_id_index.sql (Online: true, CONCURRENTLY)

CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_workflow_status_parent_workflow_id" ON "dbos"."workflow_status" ("parent_workflow_id") WHERE "parent_workflow_id" IS NOT NULL;

UPDATE "dbos".dbos_migrations SET version = 25;

-- migration 26: 26_drop_executor_id_index.sql (Online: true, CONCURRENTLY)

DROP INDEX CONCURRENTLY IF EXISTS "dbos"."workflow_status_executor_id_index";

UPDATE "dbos".dbos_migrations SET version = 26;

-- migration 27: 27_create_partial_dedup_id_index.sql (Online: true, CONCURRENTLY)

CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS "uq_workflow_status_dedup_id" ON "dbos"."workflow_status" ("queue_name", "deduplication_id") WHERE "deduplication_id" IS NOT NULL;

UPDATE "dbos".dbos_migrations SET version = 27;

-- migration 28: 28_drop_dedup_id_constraint.sql (Postgres variant; CockroachDB uses
-- 28_drop_dedup_id_constraint_cockroach.sql, a DROP INDEX instead of DROP CONSTRAINT)

ALTER TABLE "dbos".workflow_status DROP CONSTRAINT IF EXISTS uq_workflow_status_queue_name_dedup_id;

UPDATE "dbos".dbos_migrations SET version = 28;

-- migration 29: 29_create_pending_index.sql (Online: true, CONCURRENTLY)

CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_workflow_status_pending" ON "dbos"."workflow_status" ("created_at") WHERE "status" = 'PENDING';

UPDATE "dbos".dbos_migrations SET version = 29;

-- migration 30: 30_create_failed_index.sql (Online: true, CONCURRENTLY)

CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_workflow_status_failed" ON "dbos"."workflow_status" ("status", "created_at") WHERE "status" IN ('ERROR', 'CANCELLED', 'MAX_RECOVERY_ATTEMPTS_EXCEEDED');

UPDATE "dbos".dbos_migrations SET version = 30;

-- migration 31: 31_drop_status_index.sql (Online: true, CONCURRENTLY)

DROP INDEX CONCURRENTLY IF EXISTS "dbos"."workflow_status_status_index";

UPDATE "dbos".dbos_migrations SET version = 31;

-- migration 32: 32_create_in_flight_index.sql (Online: true, CONCURRENTLY)

CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_workflow_status_in_flight" ON "dbos"."workflow_status" ("queue_name", "status", "priority", "created_at") WHERE "status" IN ('ENQUEUED', 'PENDING');

UPDATE "dbos".dbos_migrations SET version = 32;

-- migration 33: 33_add_rate_limited.sql

ALTER TABLE "dbos"."workflow_status" ADD COLUMN IF NOT EXISTS "rate_limited" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE "dbos".dbos_migrations SET version = 33;

-- migration 34: 34_create_rate_limited_index.sql (Online: true, CONCURRENTLY)

CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_workflow_status_rate_limited" ON "dbos"."workflow_status" ("queue_name", "started_at_epoch_ms") WHERE "rate_limited" = TRUE;

UPDATE "dbos".dbos_migrations SET version = 34;

-- migration 35: 35_drop_queue_status_started_index.sql (Online: true, CONCURRENTLY)

DROP INDEX CONCURRENTLY IF EXISTS "dbos"."idx_workflow_status_queue_status_started";

UPDATE "dbos".dbos_migrations SET version = 35;

-- migration 36: 36_add_completed_at.sql

ALTER TABLE "dbos"."workflow_status" ADD COLUMN IF NOT EXISTS "completed_at" BIGINT;
CREATE INDEX IF NOT EXISTS "idx_workflow_status_completed_at" ON "dbos"."workflow_status" ("completed_at") WHERE "completed_at" IS NOT NULL;

UPDATE "dbos".dbos_migrations SET version = 36;

-- migration 37: 37_create_started_at_index.sql (Online: true, CONCURRENTLY)

CREATE INDEX CONCURRENTLY IF NOT EXISTS "idx_workflow_status_started_at" ON "dbos"."workflow_status" ("started_at_epoch_ms") WHERE "started_at_epoch_ms" IS NOT NULL;

UPDATE "dbos".dbos_migrations SET version = 37;

-- migration 38: 38_update_enqueue_workflow.sql

DROP FUNCTION IF EXISTS "dbos".enqueue_workflow(
    TEXT, TEXT, JSON[], JSON, TEXT, TEXT, TEXT, TEXT, BIGINT, BIGINT, TEXT, INTEGER, TEXT
);

CREATE OR REPLACE FUNCTION "dbos".enqueue_workflow(
    workflow_name TEXT,
    queue_name TEXT,
    positional_args JSON[] DEFAULT ARRAY[]::JSON[],
    named_args JSON DEFAULT '{}'::JSON,
    class_name TEXT DEFAULT NULL,
    config_name TEXT DEFAULT NULL,
    workflow_id TEXT DEFAULT NULL,
    app_version TEXT DEFAULT NULL,
    timeout_ms BIGINT DEFAULT NULL,
    deadline_epoch_ms BIGINT DEFAULT NULL,
    deduplication_id TEXT DEFAULT NULL,
    priority INT4 DEFAULT NULL,
    queue_partition_key TEXT DEFAULT NULL,
    authenticated_user TEXT DEFAULT NULL,
    authenticated_roles TEXT DEFAULT NULL,
    delay_until_epoch_ms BIGINT DEFAULT NULL
) RETURNS TEXT AS $$
DECLARE
    v_workflow_id TEXT;
    v_serialized_inputs TEXT;
    v_owner_xid TEXT;
    v_now BIGINT;
    v_recovery_attempts INT4 := 0;
    v_priority INT4;
    v_status TEXT;
BEGIN

    IF workflow_name IS NULL OR workflow_name = '' THEN
        RAISE EXCEPTION 'Workflow name cannot be null or empty';
    END IF;
    IF queue_name IS NULL OR queue_name = '' THEN
        RAISE EXCEPTION 'Queue name cannot be null or empty';
    END IF;
    IF named_args IS NOT NULL AND jsonb_typeof(named_args::jsonb) != 'object' THEN
        RAISE EXCEPTION 'Named args must be a JSON object';
    END IF;
    IF workflow_id IS NOT NULL AND workflow_id = '' THEN
        RAISE EXCEPTION 'Workflow ID cannot be an empty string if provided.';
    END IF;
    IF delay_until_epoch_ms IS NOT NULL AND delay_until_epoch_ms < 0 THEN
        RAISE EXCEPTION 'delay_until_epoch_ms must be >= 0';
    END IF;

    v_workflow_id := COALESCE(workflow_id, gen_random_uuid()::TEXT);
    v_owner_xid := gen_random_uuid()::TEXT;
    v_priority := COALESCE(priority, 0);
    v_serialized_inputs := json_build_object(
        'positionalArgs', positional_args,
        'namedArgs', named_args
    )::TEXT;
    v_now := EXTRACT(epoch FROM now()) * 1000;
    v_status := CASE WHEN delay_until_epoch_ms IS NULL THEN 'ENQUEUED' ELSE 'DELAYED' END;

    INSERT INTO "dbos".workflow_status (
        workflow_uuid, status, inputs,
        name, class_name, config_name,
        queue_name, deduplication_id, priority, queue_partition_key,
        application_version,
        created_at, updated_at, recovery_attempts,
        workflow_timeout_ms, workflow_deadline_epoch_ms,
        parent_workflow_id, owner_xid, serialization,
        authenticated_user, authenticated_roles,
        delay_until_epoch_ms
    ) VALUES (
        v_workflow_id, v_status, v_serialized_inputs,
        workflow_name, class_name, config_name,
        queue_name, deduplication_id, v_priority, queue_partition_key,
        app_version,
        v_now, v_now, v_recovery_attempts,
        timeout_ms, deadline_epoch_ms,
        NULL, v_owner_xid, 'portable_json',
        authenticated_user, authenticated_roles,
        delay_until_epoch_ms
    )
    ON CONFLICT (workflow_uuid)
    DO UPDATE SET
        updated_at = EXCLUDED.updated_at;

    RETURN v_workflow_id;

EXCEPTION
    WHEN unique_violation THEN
        RAISE EXCEPTION 'DBOS queue duplicated'
            USING DETAIL = format('Workflow %s with queue %s and deduplication ID %s already exists', v_workflow_id, queue_name, deduplication_id),
                ERRCODE = 'unique_violation';
END;
$$ LANGUAGE plpgsql;

-- migration 38: 38_set_enqueue_workflow_search_path.sql (Postgres-only tail, appended to migration 38)

ALTER FUNCTION "dbos".enqueue_workflow(
    TEXT, TEXT, JSON[], JSON, TEXT, TEXT, TEXT, TEXT, BIGINT, BIGINT, TEXT, INT4, TEXT, TEXT, TEXT, BIGINT
) SET search_path = pg_catalog, pg_temp;

UPDATE "dbos".dbos_migrations SET version = 38;

-- migration 39: 39_create_streams_trigger.sql (Postgres-only; no-op on CockroachDB)

CREATE OR REPLACE FUNCTION "dbos".streams_function() RETURNS TRIGGER AS $$
DECLARE
    payload text := NEW.workflow_uuid || '::' || NEW.key;
BEGIN
    PERFORM pg_notify('dbos_streams_channel', payload);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

ALTER FUNCTION "dbos".streams_function() SET search_path = pg_catalog, pg_temp;

DROP TRIGGER IF EXISTS dbos_streams_trigger ON "dbos".streams;
CREATE TRIGGER dbos_streams_trigger
AFTER INSERT ON "dbos".streams
FOR EACH ROW EXECUTE FUNCTION "dbos".streams_function();

UPDATE "dbos".dbos_migrations SET version = 39;

-- migration 40: 40_add_attributes.sql

ALTER TABLE "dbos"."workflow_status" ADD COLUMN IF NOT EXISTS "attributes" JSONB;
CREATE INDEX IF NOT EXISTS "idx_workflow_status_attributes" ON "dbos"."workflow_status" USING GIN ("attributes") WHERE "attributes" IS NOT NULL;

UPDATE "dbos".dbos_migrations SET version = 40;

-- migration 41: 41_add_schedule_name.sql

ALTER TABLE "dbos"."workflow_status" ADD COLUMN IF NOT EXISTS "schedule_name" TEXT;
CREATE INDEX IF NOT EXISTS "idx_workflow_status_schedule_name" ON "dbos"."workflow_status" ("schedule_name") WHERE "schedule_name" IS NOT NULL;

UPDATE "dbos".dbos_migrations SET version = 41;

-- migration 42: 42_add_debounce_columns.sql

ALTER TABLE "dbos"."workflow_status" ADD COLUMN IF NOT EXISTS "debounce_deadline_epoch_ms" BIGINT DEFAULT NULL;
ALTER TABLE "dbos"."workflow_status" ADD COLUMN IF NOT EXISTS "is_debounced" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE "dbos".dbos_migrations SET version = 42;
