defmodule Dbos.Migration do
  @moduledoc """
  Installs and removes this engine's system database schema as an explicit step in a host
  application's own Ecto migration sequence, generated by `mix dbos.gen.migration`:

      defmodule MyApp.Repo.Migrations.AddDbos do
        use Ecto.Migration

        def up, do: Dbos.Migration.up()
        def down, do: Dbos.Migration.down()
      end

  `opts[:prefix]` (default `"dbos"`) names the Postgres schema this installs into. It must
  match the `:schema` given to `Dbos.Supervisor` (also `"dbos"` by default) — the engine and
  this migration read and write the same tables under that name.

  `up/1` brings the schema up to the version this engine targets: the base tables
  (`Dbos.Migrator.expected_version/0`) and the extension tables
  (`Dbos.Migrator.expected_extension_version/0`), each guarded by its own version marker, so
  running it a second time — or against a database that already has the base schema from an
  older install — only applies what's missing. `Dbos.Migrator.create!/1` guards its own
  application of `priv/schema/dbos_schema.sql` the exact same way; both read the same
  statements from `Dbos.Migrator.schema_parts/1`, so there is exactly one place that decides
  what "the schema" is.

  `priv/schema/dbos_schema.sql` creates several indexes with `CREATE INDEX CONCURRENTLY`,
  which cannot run inside a transaction — the default for an Ecto migration.
  `CONCURRENTLY` exists to avoid locking a populated table against writes while its index
  builds; a schema `up/1` is installing is, by definition, freshly created and empty, so the
  lock `CONCURRENTLY` avoids is instant regardless. `up/1` strips `CONCURRENTLY` from every
  statement it runs, keeping the host's migration transactional instead of requiring
  `@disable_ddl_transaction true`. See `DECISIONS.md`.

  `down/1` drops every table, trigger, and function `up/1` creates. It leaves the schema
  itself (the `CREATE SCHEMA IF NOT EXISTS` from `up/1`) in place — a host may have created
  that schema, or put other objects in it, before ever running this migration, and dropping
  the whole thing out from under them is not this module's call to make.

  `opts[:version]` selects which schema version to bring the database to (`up/1`) or back from
  (`down/1`). Only one version exists today, so it currently has no effect; once a second
  version exists, `up/1` is expected to apply every version's guarded section up to and
  including the requested one (default: the latest), and `down/1` to remove every version's
  section back down to (excluding) the requested one — the same shape `Ecto.Migrator`'s own
  `:to`/`:to_exclusive` options take.
  """

  alias Dbos.Config
  alias Dbos.Migrator

  @default_prefix "dbos"

  @doc "Brings the schema up to the version this engine targets. Safe to run more than once."
  def up(opts \\ []) do
    ensure_ecto_migration_available!()
    config = ecto_config(opts)
    {base_sql, extension_sql} = Migrator.schema_parts(config.schema)

    apply_part(config, "dbos_migrations", base_sql)
    apply_part(config, "extension_migrations", extension_sql)

    :ok
  end

  @doc "Drops every table, trigger, and function `up/1` creates. Leaves the schema itself."
  def down(opts \\ []) do
    ensure_ecto_migration_available!()
    config = ecto_config(opts)

    Enum.each(drop_statements(config.schema), &Ecto.Migration.execute/1)

    :ok
  end

  @doc false
  def ensure_ecto_migration_available! do
    ensure_ecto_migration_available!(Code.ensure_loaded?(Ecto.Migration))
  end

  @doc false
  def ensure_ecto_migration_available!(loaded?) do
    unless loaded? do
      raise """
      Dbos.Migration requires Ecto.Migration, which is not loaded.

      This usually means :dbos compiled before :ecto_sql during `mix deps.compile` \
      (dbos treats ecto_sql as optional, so compile order between the two isn't guaranteed). \
      Add {:ecto_sql, "~> 3.13"} to your deps if it's missing, then run:

          mix deps.compile dbos --force
      """
    end
  end

  defp apply_part(config, marker_table, sql) do
    case Migrator.current_version(config, marker_table) do
      {:ok, _version} ->
        :ok

      {:error, :not_found} ->
        sql
        |> Migrator.statements()
        |> Enum.each(fn statement ->
          statement
          |> without_concurrently()
          |> Ecto.Migration.execute()
        end)
    end
  end

  defp without_concurrently(statement) do
    Regex.replace(~r/\bCONCURRENTLY\b\s*/i, statement, "")
  end

  defp ecto_config(opts) do
    prefix = Keyword.get(opts, :prefix, @default_prefix)
    %Config{db: Dbos.DB.Ecto, conn: Ecto.Migration.repo(), schema: prefix}
  end

  defp drop_statements(schema) do
    Enum.map(drop_tables(), &~s(DROP TABLE IF EXISTS "#{schema}".#{&1} CASCADE)) ++
      Enum.map(drop_functions(), &~s(DROP FUNCTION IF EXISTS "#{schema}".#{&1}))
  end

  defp drop_tables do
    ~w(
      extension_migrations
      executor_leases
      workflow_schedules
      application_versions
      queues
      event_dispatch_kv
      streams
      workflow_events_history
      workflow_events
      notifications
      operation_outputs
      workflow_status
      dbos_migrations
    )
  end

  defp drop_functions do
    ~w(
      enqueue_workflow
      send_message
      notifications_function
      workflow_events_function
      streams_function
    )
  end
end
